config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {   registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  root "top#index"
  resources :users, only: :show do
    resources :statuses, only: [:index]
  end

  resources :statuses, only: [:new, :create, :edit, :update]
  resources :groups, only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :message
  belongs_to :user

  validates :comment, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :messages

  validates :name, presence: true, 
            uniqueness: true,
            length: { maximum: 10 }
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user
  has_many :comments
  # imageカラムが空の場合、messageカラムも空であれば保存しない
  validates :message, presence: true, unless: :image?
end

app/models/status.rb
class Status < ApplicationRecord
  belongs_to :user

  validates :weight, :gole, presence: true,
            numericality: { only_integer: true, greater_than: 10, less_than: 300 }
  validates :rule, presence: true,
            length: { maximum: 64 }

end

app/models/user.rb
class User < ApplicationRecord
  
  belongs_to :status, optional: true
  has_many :groups
  has_many :messages
  has_many :comments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  protected
  #名前登録を許可
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index

  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.create(group_params)
    if @group.save
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def group_params
    params.require(:group).permit(:name).merge(user_id: current_user.id)
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index

  end

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController

  def index
    @status =  Status.find(params[:user_id])
  end

  def new
    @status = Status.new
  end

  def create
    @status = Status.new(status_params)
    if @status.save
      redirect_to new_group_path
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  private
  def status_params
    params.require(:status).permit(:weight, :gole, :rule).merge(user_id: current_user.id)
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @messages = Message.includes(:user).limit(10).order(id: "DESC") 
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    new_status_path
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    new_status_path
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @name = user.name
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/new.html.haml
.group
  .group-header
    - if @group.errors.any?
      %p.group-header__error ※入力情報に誤りがあります。
  .group-main
    = form_for @group do |form|
      .group-main__list
        %img{alt:"", class: "group-main__list--img", src: "/assets/cork-board.png" }
        .group-form
          .group-form__title
            %h2 ダイエット期間に名前をつけよう！
          .group-form__text-box
            %p 名付けて・・・
            = form.text_field :name, placeholder: "ex.自分大改造計画", class: "group-box form__weight-box"
            %p.length (10文字以内)
      .group-footer
        .group-footer__submit
          = form.submit "これでOK!!", class: 'group-submit__btn'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Dieter
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/messages/index.html.haml
.message

app/views/statuses/index.html.haml
.status
  .status-header
  .status-main
    .user-status-main__list
      %img{alt:"", class: "user-status-main__list--img", src: "/assets/cork-board.png" }
      .user-status-form
        .user-status-form__title
          %h2 ダイエット目標
        .user-status-form__text-box
          %ul
            %li
              ◎スタート体重：
            %li.user-weight
              = @status.weight
            %li
              kg
        .user-status-form__text-box
          %ul
            %li
              ◎目標体重：
            %li.user-weight
              = @status.gole
            %li
              kg
        .user-status-form__text-box
          %p ◎自分ルール
          .user-status-form__text-box--rule
            = @status.rule    
    .user-status-form__footer
      = link_to user_path(current_user.id), class: 'link user-status__btn' do
        戻る
      = link_to edit_status_path(current_user.id), class: 'link user-status__btn' do
        編集

app/views/statuses/new.html.haml
.status
  .status-header
    - if @status.errors.any?
      %p.status-header__error ※入力情報に誤りがあります。
  .status-main
    = form_for @status do |form|
      .status-main__list
        %img{alt:"", class: "status-main__list--img", src: "/assets/cork-board.png" }
        .status-form
          .status-form__title
            %h2 ダイエット目標をたてよう
          .status-form__info
            .status-form__text-box
              = form.label :weight, "◎スタート体重：", class: 'form__ilabel'
              = form.text_field :weight, class: "status-box form__weight-box"
              = form.label :weight, "kg", class: 'form__ilabel'
            .status-form__text-box
              = form.label :gole, "◎目標体重：", class: 'form__ilabel'
              = form.text_field :gole, class: "status-box form__gole--box"
              = form.label :weight, "kg", class: 'form__ilabel'
            %div{id: "id_rule", class:"status-form__text-box"}
              %ul
                %li
                  = form.label :gole, "◎自分ルール", class: 'form__ilabel'
                %li
                  = form.text_area :rule, placeholder: "何か一つ、ルールを決めよう。" , rows: "5", class: "form__rule"
            
      .status-footer
        .status-footer__submit
          = form.submit "これでOK!!", class: 'status-submit__btn'

app/views/top/index.html.haml
.top-page
  .top-header
    %img{alt:"", class: "top-header__logo", src: "/assets/dish.png" }
  .top-contents
    .top-contents__left
      .top-contents__left--top
        - if user_signed_in?
          = link_to user_path(current_user.id), class: "link" do
            .left-btn
              %img{alt:"", class: "icon", src: "/assets/key-rock.png" }
              %p.button-text マイページ
          = link_to destroy_user_session_path, method: :delete, class: "link" do
            .right-btn
              %img{alt:"", class: "icon", src: "/assets/create-user.png" }
              %p.button-text ログアウト
        -else
          = link_to new_user_session_path, class: "link" do
            .left-btn
              %img{alt:"", class: "icon", src: "/assets/key-open.png" }
              %p.button-text ログイン
          = link_to new_user_registration_path, class: "link" do
            .right-btn
              %img{alt:"", class: "icon", src: "/assets/create-user.png" }
              %p.button-text 新規登録
      .top-contents__left--low
        = link_to "#", class: "link" do
          .search-btn
            %p.search-text ユーザー検索
    .contents__right
      %p 最近のつぶやき
      .message-list
        - @messages.each do |message|
          .message-list__group
            = link_to "#", class: "link" do
              = truncate(message.message, length: 10, omission: "･･･")
            .message-info
              = message.user.name
              = l message.created_at
  .top-footer

app/views/users/show.html.haml
.user
  .user-header
    = @name + "の部屋"
  .user-main
    .main__room
      .main__room--image
        %img{ src: "/assets/main-room.png", alt: "", class: "main__room--img" }
        %img{ src: "/assets/big-girl.png", alt: "", class: "main__room--character" }

  .user-form
    .form__list
      = link_to root_path, class: "form__list--btn" do
        Top
      = link_to user_statuses_path(current_user.id), class: "form__list--btn" do
        目標確認
      = link_to "#", class: "form__list--btn" do
        つぶやく(工事中)
      = link_to "#", class: "form__list--btn" do
        進捗(工事）
      = link_to "#", class: "form__list--btn" do
        お気に(工事中)